<a href="https://colab.research.google.com/github/Dang-Minh-Khoi/BAITAP/blob/main/24_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.linear_model import Perceptron
x=[[0,0],[1,0],[0,1],[1,1]]
y=[0,1,1,1]
model=Perceptron()
model.fit(x,y)
model.score(x,y)


1.0

In [ ]:
x1 = [[-0.5,0.5],[10,-2],[-1,0.8],[3,5],[1,0.2],[-0.1,0.5]]
y1 = model.predict(x1)

In [ ]:
model.score(x1,y1)


1.0

In [ ]:
x2 = [[0.9,0],[0.8,0],[0.7,0],[0.6,0],[0.5,0],[0.4,0],[0.3,0]]

y2 = model.predict(x2)
model.score(x2,y2)

1.0

In [ ]:
from sklearn import datasets
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

In [ ]:
iris= datasets.load_iris()
x=iris.data
y=iris.target
print(x[:5])
print(y[:5])


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)
sc=StandardScaler()
sc.fit(x_train)
x_train_std=sc.transform(x_train)
x_test_std=sc.transform(x_test)

In [ ]:
model=Perceptron(max_iter=40,eta0=0.1,random_state=0)
model.fit(x_train_std,y_train)
y_pred = model.predict(x_test_std)
print(y_test)
print(y_test)
print('Độ chính xác của màn hình:',accuracy_score(y_test,y_pred))

[0 2 1 0 0 2 0 1 2 2 1 0 0 1 1 0 1 1 1 1 2 0 0 0 1 2 2 0 1 1 0 0 2 2 0 1 2
 1 2 0 1 1 1 2 0]
[0 2 1 0 0 2 0 1 2 2 1 0 0 1 1 0 1 1 1 1 2 0 0 0 1 2 2 0 1 1 0 0 2 2 0 1 2
 1 2 0 1 1 1 2 0]
Độ chính xác của màn hình: 0.9111111111111111


In [ ]:
import pandas as pd
url = 'crabs.csv'
data = pd.read_csv(url)
data.head()

speies sex  index  fontallip  rearwidth  length  width  depth
0      B   M      1        8.1        6.7    16.1   19.0    7.0
1      B   M      2        8.8        7.7    18.1   20.8    7.4
2      B   M      3        9.2        7.8    19.0   22.4    7.7
3      B   M      4        9.6        7.9    20.1   23.1    8.2
4      B   M      5        9.8        8.0    20.3   23.0    8.2

In [ ]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
url ='crabs.csv'
data = pd.read_csv(url)
data.head(100) #Hiện 10 thằng đầu tiên

#Chuyển bằng replace, đổi O thành 1, B thành 0. 
#Male thành 1, Female thành 0. Loài là input, output là giới tính đực hay cái, đám sau là input
#7 tín hiệu vào, 1 tín hiệu ra là giới tính

speies sex  index  fontallip  rearwidth  length  width  depth
0       B   M      1        8.1        6.7    16.1   19.0    7.0
1       B   M      2        8.8        7.7    18.1   20.8    7.4
2       B   M      3        9.2        7.8    19.0   22.4    7.7
3       B   M      4        9.6        7.9    20.1   23.1    8.2
4       B   M      5        9.8        8.0    20.3   23.0    8.2
..    ...  ..    ...        ...        ...     ...    ...    ...
95      B   F     46       16.4       14.0    34.2   39.8   15.2
96      B   F     47       16.7       16.1    36.6   41.9   15.4
97      B   F     48       17.4       16.9    38.2   44.1   16.6
98      B   F     49       17.5       16.7    38.6   44.5   17.0
99      B   F     50       19.2       16.5    40.9   47.9   18.1

[100 rows x 8 columns]

In [ ]:
data_replaced_1=data['speies'].replace(["O", "B"], [1, 0]).head(20)
data_replaced_1

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
Name: speies, dtype: int64

In [ ]:
data_replaced_2=data['sex'].replace(["M", "F"], [1, 0]).head(20)
data_replaced_2

0     1
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    1
19    1
Name: sex, dtype: int64